version: '3.8'

volumes:
  postgres-data:

services:
  app:
    container_name: c-dev
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    command: sleep infinity